config/routes.rb
Rails.application.routes.draw do
  # get 'products/:id', to: 'products#show', :as => :products
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    post 'pay', to: 'registrations#pay'
    get 'pay', to: 'registrations#pay'
  end
  
  resources :orders do
    member do
      get 'complete'
      end
	collection do
		post :callback
	end
	end
	
	resources :charges
  resources :orders
  
  resources :products do
      member do
        get 'purchase'
        get 'pay'
        post 'checkout'
        post 'document_download'
        post 'video_download'
        post 'audio_download'
        get 'info'
        end
      collection do
        get 'list'
        get 'store'
        end
      end
      
  resources :users do
        resources :orders
      end
      
  resources :users do
      member do
        get 'download'
        get 'order_list'
        end
      end
  
  # resources :users
  root :to => 'visitors#index'
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  # before_filter :authenticate_user!
  def index
    @products = Product.all.select { |m| m.stock != 0 and m.first_category == "membership"}
    
    #if user_signed_in?
    #  @products = Product.all.select { |m| (m.stock != 0 and m.id == current_user.product_id) }
    #end
    
  end
  
end

app/views/visitors/_purchase.html.erb
<a href="#" class="btn btn-primary" data-toggle="modal" data-target="#purchaseModal"><%= I18n.t('.visitors.purchase.purchase', :default => "Purchase") %></a>
<div class="modal fade" id="purchaseModal" tabindex="-1" role="dialog" aria-labelledby="purchaseModal" aria-hidden="true">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="authform">
	    <%= form_for(User.new, :url => {:controller=>'registrations', :action => 'pay'}, :html => { :role => 'form'}) do |f| %>
	      <h3>Sign Up &amp; Purchase</h3>
			<% unless product.digital %>
			<div class="form-group">
		        <%= f.text_field :name, class: 'form-control', :placeholder => "John Doe" %>
		      </div>
		      <div class="form-group">
		        <%= f.text_field :street, class: 'form-control', :placeholder => "Street Address" %>
		      </div>
			<div class="form-inline">
		        <%= f.text_field :postal_code, class: 'form-control', :style => "width:95px;", :placeholder => "Post Code" %>
		        <%= f.text_field :city, class: 'form-control', :style => "width:230px;", :placeholder => "City" %>
		      </div></br>
			<div class="form-group">
		        <% default = case I18n.locale.to_s  %>
				<%	when 'en' then 'United States' %>
				<%	when 'fr' then 'France' %>
				<%	else 'United States' %>
				<%	end %>
				<%= f.select :country, User::COUNTRIES, :selected => "#{default}" %>
		      </div>
			<% end %>


		      <div class="form-group">
	        <%= f.email_field :email, :autofocus => true, class: 'form-control', :placeholder => "Email" %>
	      </div>
	      <div class="form-group">

	        <%= f.password_field :password, class: 'form-control', :placeholder => "Password, min. 6 characters" %>
	      </div>
	      <div class="form-group">
	        <%= f.password_field :password_confirmation, class: 'form-control', :placeholder => "Password confirmation" %>
			<%= f.hidden_field :product_id, :value => product.id %>
	      </div>
		  <!--<%= recaptcha_tags :public_key => Rails.application.secrets.recaptcha_public_key %>-->
	      <%= f.submit '1. Sign up', :class => 'button left' %>
	      <%= f.submit '2. Pay', :class => 'button' , :disabled => 'disabled' %>
	    <% end %>
	  </div>
		<h5><%= link_to 'Returning customer ? Sign in', new_user_session_path %></h5>
      </div>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <h3>Admin</h3>
    <p><%= link_to 'User count:', users_path %> <%= User.count %></p>
  <% else %>
	<h3><%= t('.welcome') %></h3>
    <h4>You purchased : <%= Product.find_by_id(current_user.product_id).title if current_user.product_id %></h4>
	<p>Email: <%= current_user.email if current_user.email %></p>
	<p></p></br>
	
	<% if current_user.product_id %>
	<% @product= Product.find_by_id(current_user.product_id) %>
	<div class="container-fluid">
		<div class="row" >
			<div class="col-md-12" >
				<div class="col-md-3" >
		<span><%= image_tag @product.avatar.url(:original, false), style: "float:left;" %></span></br>
		<!--<%= link_to "Download to Browser", @product.avatar.url(:original, false),:class => 'btn btn-success btn-large' %>-->
		<% if !@product.document_file_name.blank? and current_user.purchased_product?(@product.id) %>
			<p><%= button_to t('.download_pdf', :default => "Download"),
	                document_download_product_path(@product), :action => :document_download, :class => "btn btn-success btn-small" %></p><% end %>
		<% else %>
    		<%= link_to 'Download', products_path('product.pdf'), :class => 'btn btn-success btn-large' %>
		<% end %>
				</div>
			</div></br></br>
		</div>
	</div>
  <% end %>
<% else %>
	<% if @products.count == 1 %>
	
	<h3><%= t('.checkout') %></h3>

	<div class="container-fluid">
		<div class="row" >
			<div class="col-md-12" >
				<div class="col-md-3" >
					<% @products.each do |product| %>
    				<span><%= image_tag product.avatar.url(:medium, false), style: "float:left;" %></span>

					<article style="text-align:center;">
					<%= product.title %></br></br>
					<%= number_to_currency(product.price.to_f/100, unit: "€", separator: ".", delimiter: " ", format: "%n %u") %></br>
						 <%= render partial: "visitors/purchase", locals: { :product => product } %>
					</article>
					<% end %>
    			</div>

			</div></br></br>
		</div>
	</div>
	
	<% else %>
  		<h3><%= t('.join_us') %></h3>

		<div class="container-fluid">
			<div class="row" >
			<% @products.each_slice(4) do |products_for_row| %>
				<div class="col-md-12" >
				<% products_for_row.each do |product| %>
					<div class="col-md-3" >

	    			<%= render product %>

	    			</div>
				<% end %>
				</div></br></br>
			<% end %>
			</div>
		</div>
		<% end %>

<% end %>