config/routes.rb
Rails.application.routes.draw do
  # get 'products/:id', to: 'products#show', :as => :products
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    post 'pay', to: 'registrations#pay'
    get 'pay', to: 'registrations#pay'
  end
  
  resources :orders do
    member do
      get 'complete'
      end
	collection do
		post :callback
	end
	end
	
	resources :charges
  resources :orders
  
  resources :products do
      member do
        get 'purchase'
        get 'pay'
        post 'checkout'
        post 'document_download'
        post 'video_download'
        post 'audio_download'
        get 'info'
        end
      collection do
        get 'list'
        get 'store'
        end
      end
      
  resources :users do
        resources :orders
      end
      
  resources :users do
      member do
        get 'download'
        get 'order_list'
        end
      end
  
  # resources :users
  root :to => 'visitors#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  after_initialize :set_default_pay_type, :if => :new_record?
  enum status: [:pending, :paid, :excess, :partial]
  belongs_to :user
  attr_accessor :stripeToken
  
  # serialize :content, JSON
  # @order = Order.new
  # @order.content = Hash[ [product_id: ["17","10"]], [quantity: ["1","1"]] ]
  # @order.save
  # @order.content
  #  => {[{:product_id=>["17", "10"]}]=>[{:quantity=>["1", "1"]}]} 
  # @order.content = {:make => "bmw", :year => "2003"}
  
  PAY_TYPES = ["bitcoin","card"]
  
  validates :email, :status, :presence => true
  validates :pay_type, :inclusion => PAY_TYPES
  # validates :country, :inclusion => COUNTRIES
  # validates :btc_address, :inclusion => BTC_ADDRESSES, :if => :btc_order?
  # inclusion validation commented out when using an unlimited deterministic address set (wallet)
  validates_format_of :email, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i, :multiline => true
  
  def set_default_pay_type
    self.pay_type ||= "card"
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # protect_from_forgery :except => :callback
  skip_before_filter :verify_authenticity_token, :except => [:update, :create, :index]
  # before_filter :authenticate_user!, :except => [:index, :list, :purchase, :store, :show, :info]
  # before_filter :admin_only, :except => [:download,:show, :order_list]
  
    def index
      # @orders = Order.all
      @orders = Order.order("created_at ASC").all.select { |m| User.find_by_email(m.email) }
    end
    
    def create
        
        signed_in = user_signed_in?
        if signed_in
          @product = Product.find_by_id(current_user.product_id)
        end
         
        
        if params[:stripeEmail]
          @order = Order.new(
            :email => params[:stripeEmail],
            :name => current_user.name,
            :street => current_user.street,
            :postal_code => current_user.postal_code,
            :city => current_user.city,
            :country => current_user.country,
            :currency    => 'EUR',
            :content => @product.title,
            :status    => 'paid',
            :signed_in => signed_in,
            :pay_type => 'card'
            )
        end
        
        if @order.save
          redirect_to @order, notice: 'Order was successfully created.'
         else
           render action: 'new'
        end
    end
  
    def show
      @order = Order.find(params[:id])
      
      if user_signed_in?
        @user = current_user
      else
        @user = User.find_by_email(@order.email)
      end
      
      respond_to do |format|
              format.json
              format.html
            end

    end
    
    
    def complete
      @order = Order.find(params[:id])
      
      if user_signed_in?
        @user = current_user
      else
        @user = User.find_by_email(@order.email)
      end
      
      # render js: "window.location.pathname = #{complete_order_path(@order).to_json}"
      # render :js => "window.location = '/visitors/index'"
      # redirect_to order_list_user_path(@user)
      
      respond_to do |format|
              format.json
              format.html
            end

    end
    
    
    def callback # method called only if bitcoin payment is made
      
      @btc_address = params[:payment_address]
      @order = Order.find_by_address(@btc_address)
      
      @state = params[:state]
      if @state == "processing" or @state == "paid"
        @order.status = 'paid'
        @order.pay_type = 'bitcoin'
        @order.save
        flash.now[:success] = 'Bitcoin payment received! You signed up successfully.'
      end
      render :nothing => true, :status => 200, :content_type => 'text/html'
    end
    
    
    def update
      @order = Order.find_by_id(params[:id])
      if params[:stripeEmail]
        @order.status = 'paid'
      end
      
      respond_to do |format|
        
        if @order.update(status: "paid")
          format.html { redirect_to(@order, :notice => 'Card payment received, thank you: order was successfully completed.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @order.errors, :status => :unprocessable_entity }
        end
      end
    end
    
    def destroy
      order = Order.find(params[:id])
      order.destroy
      redirect_to orders_path, :notice => "Order deleted."
    end

  private
    def secure_params
      params.require(:order).permit(:name, :address, :email, :content, :amount, :status, :balance, :pay_type, :user_id, :stripeToken, :stripeEmail, :stripeTokenType)
    end
  
    def admin_only
      unless current_user.admin?
        redirect_to :back, :alert => "Access denied."
      end
    end
  
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%- model_class = Order -%>
<%= form_for(@order, multipart: true) do |f| %>
<% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Name:' %>
    <%= f.text_field :name %>
  </div>
<div class="field">
    <%= f.label 'Content:' %>
    <%= f.text_field :content, :style => "width: 450px;height: 100px;", :default => @order.content %>
  </div>
<div class="field">
    <%= f.label 'Amount:' %>
    <%= f.text_field :amount %>
  </div>
<div class="field">
    <%= f.label 'Street:' %>
	<%= f.select :street %>
  </div>
<div class="field">
    <%= f.label 'Postal code:' %>
	<%= f.select :postal_code %>
  </div>
<div class="field">
    <%= f.label 'City:' %>
	<%= f.select :city %>
  </div>

<div class="field">
    <%= f.label 'Country:' %>
	<%= f.select :country, Product::COUNTRIES, :selected => "#{@order.country}" %>
  </div>

<div class="field">
    <%= f.label 'Pay type:' %>
	<%= f.text_field :pay_type, :default => @order.pay_type %>
  </div>

<div class="field">
    <%= f.label 'BTC Address:' %>
    <%= f.file_field :address %>
  </div>


	
<div class="actions">
	<% if @order.id %>
		<%= f.submit 'Update', class: "btn btn-primary btn-small", style: "background-color:blue;color:white;" %>
	<% else %>
		<%= f.submit 'Create', class: "btn btn-primary btn-small", style: "background-color:blue;color:white;" %>
	<% end %>
	
	<%= link_to 'Cancel', orders_path, class: 'btn btn-small', style: "background-color:gainsboro;color:black;" %>
	  </div>
	<% end %>

app/views/orders/_order.html.erb
<tr>
<td><%= order.id %></td>
<td><%= order.name %></td>
<td><%= order.email %></td>
<td><%= order.pay_type %></td>
<td><%= number_to_currency(order.amount, unit: "€", separator: ".", delimiter: " ", format: "%n %u") %></td>
<td><%= order.content %></td>
<td><%= order.address %></td>
<td><%= order.status %></td>
<td><%= link_to "Show", order_path(order), :class => 'btn btn-default btn-xs' %></td>
<td><%= link_to "Edit", edit_order_path(order), :class => 'btn btn-default btn-xs btn-success' %></td>
<td><%= link_to "Delete", order_path(order), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-default btn-xs btn-danger' %></td>
</tr>

app/views/orders/complete.html.erb
<% @product= Product.find_by_title(@order.content) %>
</br></br><h4>Order # <%= @order.id %></h4>
<div class="container-fluid">
	<div class="row" >
		<div class="col-md-6" >
<div class="table-responsive">
<table class="table table-condensed table-bordered">
<tr class="something"><td class="col-md-2">Account</td><td class="col-md-6"><b><%= @order.email %></b></td>
<tr><td>Date</td><td><b><%= @order.created_at.strftime("%d/%m/%Y") %></b></td>

<tr><td class="col-md-2">Amount</td><td class="col-md-4"><b><%= number_to_currency(@order.amount, unit: "€", separator: ".", delimiter: " ", format: "%n %u") %></b></td>

<tr><td class="col-md-2">Content</td><td class="col-md-4"><b><%= @order.content %></b></td>

<tr><td class="col-md-2">Payment type</td><td class="col-md-4"><b><%= @order.pay_type %></b></td>

<tr><td class="col-md-2">Status</td><td class="col-md-4"><b><%= @order.status %></b></td>
	
<tr><td class="col-md-2">Bitcoin Address</td><td class="col-md-4"><b><%= @order.address %></b></td>
<% unless @product.digital or @order.city.blank? %>
<tr><td class="col-md-2">Delivery Address</td><td class="col-md-4"><b><%= @order.name %> | <%= @order.street %> | <%= @order.postal_code %> | <%= @order.city %> | <%= @order.country %></b></td>
<% end %>

</table>
</div>

<div class="col-md-6" >
	</div>

</div>
</div>
</div>

	<div><%= image_tag @product.avatar.url(:original, false), style: "float:left;" %></div></br>
	<!--<%= link_to "Download to Browser", @product.avatar.url(:original, false),:class => 'btn btn-success btn-large' %>-->
	<% if !@product.document_file_name.blank? and @order.status == 'paid' %>
	<p><%= button_to t('.download_doc', :default => "Download document"),
                document_download_product_path(@product), :action => :document_download, :class => "btn btn-success btn-small" %></p>
	<% end %>
	<% if @order.status == 'pending' %>
	<% price = ((@order.amount*100).to_i > $MIN_STRIPE_AMOUNT ? (@order.amount*100).to_i : $MIN_STRIPE_AMOUNT) %>
	<div id="my-buttons">

	       <script src="https://checkout.stripe.com/v2/checkout.js"
	        class="stripe-button"
	        data-label="Pay with card"
	        data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
			data-image="<%= image_path('logo_bitcoin_france_transparent.png') %>"
			data-email="<%= current_user.email %>"
	        data-description="<%= @order.content %>"
	        data-amount="<%= price %>"

			data-currency="<%= @order.currency %>"
			onclick="myFunction()"
			>
	       </script>
	</div>
	<% end %>

app/views/orders/edit.html.erb
<h3>Editing order</h3>
<%- model_class = Order -%>
<%= form_for(@order, multipart: true) do |f| %>
<% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Name:' %>
    <%= f.text_field :name %>
  </div>
<div class="field">
    <%= f.label 'Content:' %>
    <%= f.text_field :content, :style => "width: 450px;height: 100px;", :default => @order.content %>
  </div>
<div class="field">
    <%= f.label 'Amount:' %>
    <%= f.text_field :amount %>
  </div>
<div class="field">
    <%= f.label 'Street:' %>
	<%= f.text_field :street %>
  </div>
<div class="field">
    <%= f.label 'Postal code:' %>
	<%= f.text_field :postal_code %>
  </div>
<div class="field">
    <%= f.label 'City:' %>
	<%= f.text_field :city %>
  </div>

<div class="field">
    <%= f.label 'Country:' %>
	<%= f.select :country, User::COUNTRIES, :selected => "#{@order.country}" %>
  </div>

<div class="field">
    <%= f.label 'Pay type:' %>
	<%= f.select :pay_type, Order::PAY_TYPES, :default => @order.pay_type %>
  </div>

<div class="field">
    <%= f.label 'BTC Address:' %>
    <%= f.text_field :address %>
  </div>


	
<div class="actions">
	<% if @order.id %>
		<%= f.submit 'Update', class: "btn btn-primary btn-small", style: "background-color:blue;color:white;" %>
	<% else %>
		<%= f.submit 'Create', class: "btn btn-primary btn-small", style: "background-color:blue;color:white;" %>
	<% end %>
	
	<%= link_to 'Back', orders_path, class: 'btn btn-small', style: "background-color:gainsboro;color:black;" %>
	  </div>
	<% end %>

app/views/orders/index.html.erb
</br></br></br>
<h4><%= pluralize( @orders.count, 'order' ) %></h4>
<table class="table table-condensed table-hover">
	<th>
		<td><%= t('.name') %></td>
		<td><%= t('.email') %></td>
		<td><%= t('.pay_type') %></td>
		<td><%= t('.amount') %></td>
		<td><%= t('.content') %></td>
		<td><%= t('.btc_address') %></td>
		<td><%= t('.status') %></td>
		<td> </td>
	</th>
	<% @orders.each do |order| %>
			<%= render order %>
		<% end %>
</table>
<%= link_to 'Back', root_path, class: 'btn btn-small', style: "background-color:gainsboro;color:black;" %>

app/views/orders/show.html.erb
<% @product= Product.find_by_title(@order.content) %>
</br></br><h4>Order # <%= @order.id %></h4>
<div class="container-fluid">
	<div class="row" >
		<div class="col-md-6" >
<div class="table-responsive">
<table class="table table-condensed table-bordered">
<tr class="something"><td class="col-md-2">Account</td><td class="col-md-6"><b><%= @order.email %></b></td>
<tr><td>Date</td><td><b><%= @order.created_at.strftime("%d/%m/%Y") %></b></td>

<tr><td class="col-md-2">Amount</td><td class="col-md-4"><b><%= number_to_currency(@order.amount, unit: "€", separator: ".", delimiter: " ", format: "%n %u") %></b></td>

<tr><td class="col-md-2">Content</td><td class="col-md-4"><b><%= @order.content %></b></td>

<tr><td class="col-md-2">Payment type</td><td class="col-md-4"><b><%= @order.pay_type %></b></td>

<tr><td class="col-md-2">Status</td><td class="col-md-4"><b><%= @order.status %></b></td>
	
<tr><td class="col-md-2">Bitcoin Address</td><td class="col-md-4"><b><%= @order.address %></b></td>
<% unless @product.digital or @order.city.blank? %>
<tr><td class="col-md-2">Delivery Address</td><td class="col-md-4"><b><%= @order.name %> | <%= @order.street %> | <%= @order.postal_code %> | <%= @order.city %> | <%= @order.country %></b></td>
<% end %>

</table>
</div>

<div class="col-md-6" >
	</div>

</div>
</div>
</div>
<div class="container-fluid">
	<div class="row" >
		<div class="col-md-12" >
			<div class="col-md-3" >
	<span><%= image_tag @product.avatar.url(:original, false), style: "float:left;" %></span></br>
	<!--<%= link_to "Download to Browser", @product.avatar.url(:original, false),:class => 'btn btn-success btn-large' %>-->
	<% if @product.has_attachment? and @order.status == 'paid' %> 
	<% if current_user %>
		<% if current_user.admin? %>
			<%= link_to 'Edit',edit_product_path(@product), :class => 'btn btn-primary btn-small' %>
			<%= link_to "Delete", product_path(@product), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-default btn-xs btn-danger' %>
		<% end %>
		<% if current_user.purchased_product?(@product.id) and @product.digital %>
			<% case @product.second_category %>
			<% when "video" %>
				<%= button_to t('.download_video', :default => "Download video"),
	                video_download_product_path(@product), :action => :document_download, :class => "btn btn-success btn-small" %>
			<% when "audio" %>
				<%= button_to t('.download_audio', :default => "Download"),
			                audio_download_product_path(@product), :action => :document_download, :class => "btn btn-success btn-small" %>
			<% else %>
			<%= button_to t('.download_document', :default => "Download document"),
	                document_download_product_path(@product), :action => :document_download, :class => "btn btn-success btn-small" %>
			<% end %>
		<% else %>
		<%= number_to_currency(@product.price.to_f/100, unit: "€", separator: ".", delimiter: " ", format: "%n %u") %></br>
		<%= link_to 'Order', checkout_product_path(@product), :method => 'post', :class => 'btn btn-primary btn-small' %>
		<% end %>
	<% else %>
		<%= number_to_currency(@product.price.to_f/100, unit: "€", separator: ".", delimiter: " ", format: "%n %u") %></br>
		<% button_label = @product.first_category == "membership" ? 'Sign up' : 'Order' %>
		<%= link_to button_label , purchase_product_path(@product), :class => 'btn btn-primary btn-small' %>
	<% end %>
	<% end %>
			</div>
		</div></br></br>
	</div>
</div>
	
	<% if @order.status == 'pending' %>
	<% price = ((@order.amount*100).to_i > $MIN_STRIPE_AMOUNT ? (@order.amount*100).to_i : $MIN_STRIPE_AMOUNT) %>
	<div id="my-buttons">

	       <script src="https://checkout.stripe.com/v2/checkout.js"
	        class="stripe-button"
	        data-label="Pay with card"
	        data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
			data-image="<%= image_path('logo_bitcoin_france_transparent.png') %>"
			data-email="<%= current_user.email %>"
	        data-description="<%= @order.content %>"
	        data-amount="<%= price %>"

			data-currency="<%= @order.currency %>"
			onclick="myFunction()"
			>
	       </script>
	</div>
	<% end %>

app/views/orders/show.json.erb
{
    "email": "<%= @order.email.to_json %>",
    "address": "<%= @order.address.to_json %>",
	"signedin": "<%= @order.signed_in.to_s.to_json %>",
	"state": "<%= @order.status.to_json %>"
}