config/routes.rb
Rails.application.routes.draw do
  # get 'products/:id', to: 'products#show', :as => :products
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    post 'pay', to: 'registrations#pay'
    get 'pay', to: 'registrations#pay'
  end
  
  resources :orders do
    member do
      get 'complete'
      end
	collection do
		post :callback
	end
	end
	
	resources :charges
  resources :orders
  
  resources :products do
      member do
        get 'purchase'
        get 'pay'
        post 'checkout'
        post 'document_download'
        post 'video_download'
        post 'audio_download'
        get 'info'
        end
      collection do
        get 'list'
        get 'store'
        end
      end
      
  resources :users do
        resources :orders
      end
      
  resources :users do
      member do
        get 'download'
        get 'order_list'
        end
      end
  
  # resources :users
  root :to => 'visitors#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  has_attached_file :avatar, styles: {
     thumb: '100x100>',
     square: '200x200#',
     medium: '300x300>'
   }, :default_url => "/images/:style/missing.png",
   :storage => :s3,
   :s3_permissions => :public_read,
   :s3_credentials => "#{Rails.root}/config/aws.yml",
   :bucket => 'hashtree-assets',
   :s3_options => { :server => "s3-eu-west-1.amazonaws.com" }

   validates_attachment :avatar,
     :size => { :in => 0..$MAX_FILE_SIZE.kilobytes }
   
   # validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
   
   validates_attachment :avatar, :content_type => { :content_type => ["image/jpeg", "image/png"] }
   validates_attachment_file_name :avatar, :matches => [/png\Z/, /jpe?g\Z/, /mp3\Z/, /mp4\Z/,/epub\Z/,/pdf\Z/]
   # Explicitly do not validate
   do_not_validate_attachment_file_type :avatar
   
   
   has_attached_file :document
   
   has_attached_file :document,
    :storage => :s3,
    :s3_permissions => :public_read,
    :s3_credentials => "#{Rails.root}/config/aws.yml",
    :bucket => 'hashtree-assets',
    :s3_options => { :server => "s3-eu-west-1.amazonaws.com" }
   

   # validates_attachment_presence :document
   validates_attachment_content_type :document, :content_type => [ 'application/pdf','text/plain',"application/epub+zip","application/octet-stream","application/zip"]
   validates_attachment_file_name :document, :matches => [/png\Z/, /jpe?g\Z/,/epub\Z/,/pdf\Z/,/webarchive\Z/,/zip\Z/]
   validates_attachment :document,
      :size => { :in => 0..$MAX_FILE_SIZE.kilobytes }
   do_not_validate_attachment_file_type :document

   has_attached_file :audio
   # validates_attachment_presence :audio
   validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']
   validates_attachment_file_name :audio, :matches => [/mp3\Z/, /mp4\Z/]
   validates_attachment :audio,
      :size => { :in => 0..$MAX_FILE_SIZE.kilobytes }
   
   has_attached_file :video
   # validates_attachment_presence :video
   validates_attachment_content_type :video, :content_type => [ 'video/mp4','video/mpeg']
   validates_attachment_file_name :video, :matches => [/mp4\Z/]
   validates_attachment :video,
      :size => { :in => 0..$MAX_FILE_SIZE.kilobytes }

  has_many :line_items
  has_many :orders, :through => :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  after_initialize :set_default_stock, :if => :new_record?
  
  CATEGORIES = ["ebook","paperback","membership", "music"]
  
  DOC_TYPES = ["pdf", "epub", "webarchive","zip","video", "audio"]
  
  def set_default_stock
    self.stock ||= 1
  end
  
  def has_attachment?
    !self.document_file_name.blank? or ( !self.audio_file_name.blank? or !self.video_file_name.blank?)
  end
  

  private
  # ensure that there are no line items referencing this product

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items Present')
      return false
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :list, :purchase, :store, :show, :info]
  # before_filter :identify_product, :except => [:index, :list, :purchase, :new, :create,:document_download, :edit, :show]
  
  
  def info
    @product = Product.find(params[:id])
  end
  
  def document_download
     @product = Product.find(params[:id])
     @file = "product_" + @product.id.to_s
     @path = @product.document.url
      if !@path.nil?
        data = open(@path) 
        
        case @product.second_category
        when "epub"
          send_data data.read, filename: "monfichier.epub", type: "application/epub+zip", disposition: 'attachment', stream: 'true', buffer_size: '4096'
        when "pdf"
          send_data data.read, filename: "monfichier.pdf", type: "application/pdf", disposition: 'attachment', stream: 'true', buffer_size: '4096'
        when "webarchive"
          send_data data.read, filename: "monfichier.webarchive", type: "application/octet-stream", disposition: 'attachment', stream: 'true', buffer_size: '4096'
        when "zip"
          send_data data.read, filename: "monfichier.zip", type: "application/zip", disposition: 'attachment', stream: 'true', buffer_size: '4096'
        else
          redirect_to store_products_path
        end
        
      else 
         redirect_to store_products_path
      end
  end

  def video_download
     @product = Product.find(params[:id])
     @path = @product.video.url
     if !@path.nil?
      data = open(@path) 
      send_data data.read, filename: "monfichier.mp4", type: "video/mp4", disposition: 'attachment', stream: 'true', buffer_size: '4096'
    else 
      redirect_to store_products_path
    end
  end
  
  def audio_download
     @product = Product.find(params[:id])
     @path = @product.audio.url
     if !@path.nil?
      data = open(@path) 
      send_data data.read, filename: "monfichier.mp3", type: "audio/mp3", disposition: 'attachment', stream: 'true', buffer_size: '4096'
    else 
      redirect_to store_products_path
    end
  end

  def default_download
     @product = Product.find(params[:id])
      file_path = @product.audio_file_name
      if !file_path.nil?
  send_file "#{Rails.root}/public/system/audios/#{@product.id}/original/#{file_path}", :x_sendfile => true 
  else 
         redirect_to store_products_path
  end
  end
  
  def list
    @products = Product.all
  end
  
  def index
    @products = Product.all
  end
  
  def store
    @products = Product.all.select { |m| m.stock != 0 and m.first_category != "membership" }
  end
  
  def new
    @product = Product.new
  end

  def show
    @product = Product.find_by_id(params[:id])
    # send_file @path, :disposition => "attachment; filename=#{@file}"
  end
  
  
  def purchase
      @products = Product.where(id: params[:id]).to_a
      render "visitors/index"
  end
  
  def pay
      # @products = Product.where(id: params[:id]).to_a
      @product = Product.find_by_id(params[:id])
      respond_to do |format|
          # that will mean to send a javascript code to client-side;
          format.js { render :action => "pay" }
          format.html { render :action => "pay" }
        end
  end
  
  def checkout
      # @products = Product.where(id: params[:id]).to_a
      @product = Product.find_by_id(params[:id])
      @user = current_user  # checkout method is called only when user is signed in
      @user.product_id = @product.id
      @user.save
      
      @orders = Order.all.select { |m| m.email == @user.email and m.status == "pending" }
      unless @orders.blank?
      @orders.each do |order|
        order.destroy
        end 
      end
      
      # product = @product
      @amount = @product.price.to_i/100.0 # price in EUR
      
      @order = Order.create(
        :email => current_user.email,
        :name => current_user.name,
        :street => current_user.street,
        :postal_code => current_user.postal_code,
        :city => current_user.city,
        :country => current_user.country,
        :amount => "#{@amount}",
        :content => "#{@product.title}",
        :currency    => 'EUR',
        :status    => 'pending',
        :pay_type => 'card',
        :signed_in => true,
        :user_id => current_user.id
        )
        
        if @order.save
          # using paymium_api gem:
          @client = Paymium::Api::Client.new  host: 'https://paymium.com/api/v1',
                                              key: Rails.application.secrets.paymium_api_key,
                                              secret: Rails.application.secrets.paymium_secret_key

          payment_request = @client.post '/merchant/create_payment',  amount:"#{@order.amount}" , 
                                                                      payment_split:"0", 
                                                                      currency:"EUR",
                                                                      callback_url: "#{$ORDERS_URL}callback"

          @order.address = payment_request["payment_address"]
          @btc_amount = payment_request["btc_amount"].to_s
          @expiry = payment_request["expires_at"]

          @order.balance = @btc_amount.to_d
    		  @order.qrcode_string = "bitcoin:#{@order.address}?amount=#{@btc_amount}" # warning: make sure the number of decimals here matches that of the Paymium API
    		  @order.expiry = Time.at(@expiry.to_i).to_datetime
          @order.save

          end
      
  end
  
  
  def create
      @product = Product.new(product_params)

      if @product.save
        redirect_to @product, notice: 'Product was successfully created.'
       else
         render action: 'new'
      end
  end
    
  def edit
    @product = Product.find_by_id(params[:id])
  end
  
  def update
    @product = Product.find_by_id(params[:id])
    
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end
    
  def destroy
    @product = Product.find_by_id(params[:id])
    @product.destroy
    @products = Product.all
    redirect_to list_products_path, notice: 'Product was successfully deleted.'
  end

  private
  
  def product_params
      params.require(:product).permit(:avatar,:document,:audio,:video, :title, :description,:price, :first_category,:second_category, :digital, :stock)
    end
  
  
  def identify_product
    valid_characters = "^[0-9a-zA-Z]*$".freeze
    unless params[:id].blank?
      @product_id = params[:id]
      @product_id = @product_id.tr("^#{valid_characters}", '')
    else
      raise "Filename missing"
    end
    unless params[:format].blank?
      @format = params[:format]
      @format = @format.tr("^#{valid_characters}", '')
    else
      raise "File extension missing"
    end
    @path = "app/views/products/#{@product_id}.#{@format}"
    @file = "#{@product_id}.#{@format}"
  end

end

app/views/products/_form.html.erb
<%- model_class = Product -%>
<%= form_for(@product, multipart: true) do |f| %>
<% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Title:' %>
    <%= f.text_field :title %>
  </div>
<div class="field">
    <%= f.label 'Description:' %>
    <%= f.text_field :description, :style => "width: 450px;height: 100px;", :default => @product.description %>
  </div>
<div class="field">
    <%= f.label 'Price in eurocents:' %>
    <%= f.text_field :price, :placeholder => "Price in eurocents, e.g. 99 for 0,99 €", :style => "width: 250px;" %>
  </div>
<div class="field">
    <%= f.label '1st Category:' %>
	<%= f.select :first_category, Product::CATEGORIES, :selected => "#{@product.first_category}" %>
  </div>

<div class="field">
    <%= f.label '2nd Category:' %>
	<%= f.select :second_category, Product::DOC_TYPES, :selected => "#{@product.second_category}" %>
  </div>

<div class="field">
    <%= f.label 'Stock:' %>
	<%= f.text_field :stock, :default => @product.stock %>
  </div>

<div class="field">
    <%= f.label 'Dgital:' %>
	<%= f.check_box :digital, :default => @product.digital %>
  </div>

<div class="field">
    <%= f.label 'Photo*:' %>
    <%= f.file_field :avatar %>
  </div>

<div class="field">
    <%= f.label 'Document*:' %>
    <%= f.file_field :document %>
  </div>

<div class="field">
    <%= f.label 'Audio*:' %>
    <%= f.file_field :audio %>
  </div>

<div class="field">
    <%= f.label 'Video*:' %>
    <%= f.file_field :video %>
  </div>


	
<div class="actions">
	<% if @product.id %>
		<%= f.submit 'Update', class: "btn btn-primary btn-small", style: "background-color:blue;color:white;" %>
	<% else %>
		<%= f.submit 'Create', class: "btn btn-primary btn-small", style: "background-color:blue;color:white;" %>
	<% end %>
	
	<%= link_to 'Cancel', products_path, class: 'btn btn-small', style: "background-color:gainsboro;color:black;" %>
	  </div>
	<% end %>
<aside>* File image format: png, jpg</aside>
<aside>* Image height: 300 px for correct display alignment</aside>
<aside>* Document file format: png, jpg, epub, pdf, webarchive </aside>
<aside>* Audio file format: mp3, mp4 </aside>
<aside>* Video file format: mp4 </aside>
<aside>* Attachment size: less than <%= $MAX_FILE_SIZE %> kilobytes</aside>

app/views/products/_product.html.erb
<!-- product image + link to trigger modal display -->
<div style="height: 300px;"><a href="#" data-toggle="modal" data-target="#exampleModal" data-producttitle="<%= product.title %>" data-productprice="<%= product.price %>" data-productdescription="<%= product.description %>" data-productfirstcat="<%= product.first_category %>" data-productsecondcat="<%= product.second_category %>" data-productphotourl="<%= product.avatar.url(:square) %>" data-productdocument="<%= product.document_file_name %>" ><%= image_tag product.avatar.url(:original, false),  :class => "img-rounded" %></a></div>

<!-- Modal -->

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= @products.first.title %></h4>
      </div>
      <div class="modal-body">

        <form>
		  <img id="product-photo" src="" class="img-rounded"/>
          <div class="form-group">
            <label for="product-price" class="control-label">Price:</label>
            <input type="text" class="form-control" id="product-price">
          </div>
          <div class="form-group">
            <label for="product-description" class="control-label">Description:</label>
            <textarea class="form-control" id="product-description"></textarea>
          </div>
		
        </form>
      </div>
    </div>
  </div>
</div>

<!-- product info -->
<article style="text-align:center;display: block;margin-left:auto;margin-right:auto;margin-bottom:0;margin-top:auto;">
<%= product.title %></br></br>

	<% if current_user %>
		<% if current_user.admin? %>
			<%= link_to 'Edit',edit_product_path(product), :class => 'btn btn-primary btn-small' %>
			<%= link_to "Delete", product_path(product), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-default btn-xs btn-danger' %>
		<% end %>
		<% if current_user.purchased_product?(product.id) and product.digital %>
			<% case product.second_category %>
			<% when "video" %>
				<%= button_to I18n.t('.products.store.product.download_video', :default => "Download video"),
	                video_download_product_path(product), :action => :document_download, :class => "btn btn-success btn-small" %>
			<% when "audio" %>
				<%= button_to I18n.t('.products.store.product.download_audio', :default => "Download"),
			                audio_download_product_path(product), :action => :document_download, :class => "btn btn-success btn-small" %>
			<% else %>
			<%= button_to I18n.t('.products.store.product.download_document', :default => "Download document"),
	                document_download_product_path(product), :action => :document_download, :class => "btn btn-success btn-small" %>
			<% end %>
		<% else %>
		<%= number_to_currency(product.price.to_f/100, unit: "€", separator: ".", delimiter: " ", format: "%n %u") %></br>
		<%= link_to I18n.t('.products.store.product.order'), checkout_product_path(product), :method => 'post', :class => 'btn btn-primary btn-small' %>
		<% end %>
	<% else %>
		<%= number_to_currency(product.price.to_f/100, unit: "€", separator: ".", delimiter: " ", format: "%n %u") %></br>
		<% button_label = product.first_category == "membership" ? I18n.t('.products.store.product.sign_up') : I18n.t('.products.store.product.order') %>
		<%= link_to button_label , purchase_product_path(product), :class => 'btn btn-primary btn-small' %>
	<% end %>
</article>
</br></br>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<ul id='products'>
	<h5><%= render @products %></h5>
</ul>
<% if current_user.admin? %>
<%= link_to 'New product', new_product_path %>
<% end %>

app/views/products/list.html.erb
<ul id='products'>
	<h5><%= render @products %></h5>
</ul>
<% if current_user.admin? %>
<%= link_to 'New product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h3>New product</h3>

<%= render 'form' %>

app/views/products/purchase.html.erb
<a href="#" class="btn btn-primary" data-toggle="modal" data-target="#purchaseModal"><%= t('.purchase') %></a>
<div class="modal fade" id="purchaseModal" tabindex="-1" role="dialog" aria-labelledby="purchaseModal" aria-hidden="true">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="authform">
	    <%= form_for(Order.new, :url => {:controller=>'orders', :action => 'pay'}, :html => { :role => 'form'}) do |f| %>
	      <h3><%= t('.purchase') %></h3>
			<% unless product.digital %>
			<div class="form-group">
		        <%= f.text_field :name, class: 'form-control', :placeholder => "#{current_user.name}" %>
		      </div>
		      <div class="form-group">
		        <%= f.text_field :street, class: 'form-control', :placeholder => "#{current_user.street}" %>
		      </div>
			<div class="form-inline">
		        <%= f.text_field :postal_code, class: 'form-control', :style => "width:95px;", :placeholder => "#{current_user.postal_code}" %>
		        <%= f.text_field :city, class: 'form-control', :style => "width:230px;", :placeholder => "#{current_user.city}" %>
		      </div></br>
			<div class="form-group">
				<%= f.select :country, User::COUNTRIES, :selected => "#{current_user.country}" %>
		      </div>
			<% end %>


		      <div class="form-group">
	        <%= f.email_field :email, :autofocus => true, class: 'form-control', :placeholder => "#{current_user.email}", disabled: 'true' %>
	      </div>

	      <div class="form-group">
			<%= f.hidden_field :product_id, :value => product.id %>
	      </div>
		  <!--<%= recaptcha_tags :public_key => Rails.application.secrets.recaptcha_public_key %>-->
	      <%= link_to 'Cancel', product_path(@product), :class => 'button left' %>
	      <%= f.submit 'Continue', :class => 'button' %>
	    <% end %>
	  </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<p>
	<%= image_tag @product.avatar.url(:square) %>
</p>
<p>
	<%= @product.title %>
</p>
<%= number_to_currency(@product.price.to_f/100, unit: "€", separator: ".", delimiter: " ", format: "%n %u") %></br>
<b>1st Category:</b>
<%= @product.first_category %></br>
<b>2nd Category:</b>
<%= @product.second_category %></br>
<b>Stock:</b>
<%= @product.stock %></br>
<b>Digital?</b>
<%= @product.digital %></br>
<b>Description:</b>
<%= @product.description %></br>
<b>Document:</b>
<%= @product.document_file_name %></br>
<b>Audio:</b>
<%= @product.audio_file_name %></br>
<b>Video:</b>
<%= @product.video_file_name %></br>

app/views/products/store.html.erb
<h3><%= t('.select') %></h3>



<div class="container-fluid">
	<div class="row" >
	<% @products.each_slice(4) do |products_for_row| %>
		<div class="col-md-12" >
		<% products_for_row.each do |product| %>
			<div class="col-md-3" style="height: 500px;" >

			<%= render product %>

			</div>
		<% end %>
		</div></br></br>
	<% end %>
	</div>
	
</div>