config/routes.rb
Rails.application.routes.draw do
  # get 'products/:id', to: 'products#show', :as => :products
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
  
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    post 'pay', to: 'registrations#pay'
    get 'pay', to: 'registrations#pay'
  end
  
  resources :orders do
    member do
      get 'complete'
      end
	collection do
		post :callback
	end
	end
	
	resources :charges
  resources :orders
  
  resources :products do
      member do
        get 'purchase'
        get 'pay'
        post 'checkout'
        post 'document_download'
        post 'video_download'
        post 'audio_download'
        get 'info'
        end
      collection do
        get 'list'
        get 'store'
        end
      end
      
  resources :users do
        resources :orders
      end
      
  resources :users do
      member do
        get 'download'
        get 'order_list'
        end
      end
  
  # resources :users
  root :to => 'visitors#index'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    E-commerce demo site - <a href="https://github.com/pierrenoizat" target="_blank"><%= t('.submit_issues') %>Github</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t('.about'),   static_pages_about_path %></li>
      <li><a href="http://www.e-ducat.fr" style="color:rgb(0,0,0);" target="_blank">blog</a></li>
	  
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : (name == 'info' ? 'info' : 'danger' )%>">

      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_modal.html.erb
<div id="ajax-modal" class="modal hide fade" tabindex="-1">
  <div class='modal-header'>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title">Campustask</h3>
  </div>
  <div class='modal-body'>
    <div class="modal-body-content"></div>
    <div class="ajax-loader"></div>
  </div>
  <div class='modal-footer'>
    <button type="button" data-dismiss="modal" class="btn">Close</button>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<!--<nav class="navbar navbar-inverse navbar-fixed-top">-->
<nav class="navbar navbar-custom">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
		<span class="icon-bar"></span>
      </button>
      <%= link_to t('.home'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
	  </ul>
	
	  <ul class="nav navbar-nav navbar-right">

		<% if user_signed_in? %>

		  <% if current_user.admin? %>
			<li><%= link_to 'Products', list_products_path %></li>
			<li><%= link_to 'Orders', orders_path %></li>
			
		  <% end %>

		<li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><%= link_to 'My Orders', order_list_user_path(current_user) %></li>
		            <li><%= link_to 'Edit account', edit_user_registration_path %></li>
		            <li class="divider"></li>
		            <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
		          </ul>
		        </li>
		
		<% else %>

			<li><%= link_to t('.sign_in'), new_user_session_path %></li>
			<!--<li><%= link_to 'Sign up', new_user_registration_path %></li>-->
		<% end %>

		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown"><ul class="f32"><li class="flag <%= "#{set_flag_id(I18n.locale)}" %>"></li></ul></a>
				<ul class="dropdown-menu">

					<% names = { :fr => 'Français', :en =>'English' }.with_indifferent_access %>
				    <% I18n.available_locales.each do |l| %>

						<li class="locale">
					    	<%= link_to({ :l => l, :r => params[:r] }) do %>
					
							<ul class="f32">
							  <li class="flag <%= "#{set_flag_id(l)}" %>"></li></br><span><%= set_flag_string(l) %></span>
							</ul>
		
							<% end %>

						</li>
						<% end %>
						
				</ul>
		</li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to t('.store'), store_products_path %></li>
<li><%= link_to t('.about'), static_pages_about_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Paymium Stripe Checkout" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Paymium Stripe Checkout" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

	<%= stylesheet_link_tag "application", :media => "all" %>
	<link
	    rel="stylesheet"
	    type="text/css"
	    href="http://cloud.github.com/downloads/lafeber/world-flags-sprite/flags32.css"
	/>
	
	<%#= For third-generation iPad with high-resolution Retina display: %>
    <%#= Size should be 144 x 144 pixels %>
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <%#= For iPhone with high-resolution Retina display: %>
    <%#= Size should be 114 x 114 pixels %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <%#= For first- and second-generation iPad: %>
    <%#= Size should be 72 x 72 pixels %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <%#= For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: %>
    <%#= Size should be 57 x 57 pixels %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <%#= For all other devices %>
    <%#= Size should be 32 x 32 pixels %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

	<script src='https://www.google.com/recaptcha/api.js'></script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
	
		<div class="container">
			<%= render 'layouts/messages' %>
			
		      <%= yield %>
		      <%= render 'layouts/footer' %>
		    </div>
    </main>
  </body>
</html>